---
title: Additional resources
bibliography: Resources/biblio_web.bib
format:
  html:
    page-layout: full
---

## {{< iconify fa-solid:pen-nib >}} &nbsp; Scientific writing 


::: {.talk-card}

### General tips and tools

* The package [microtype](https://ctan.org/pkg/microtype) helps improving the rendering of long text easily
* [Quarto](https://quarto.org/) is an open-source librairy that enables to create dynamic scientific documents, presentations, and websites using Markdown, LaTeX, and a variety of programming languages (including python, R, etc.).
  * The html presentations can then be translated into pdfs using [decktape](https://github.com/astefanutti/decktape). 
    * install node ```brew install node```
    * install decktape ``` npm install -g decktape ```
    * ```reveal --size=1600x1000 presentation.html presentation.pdf```  

:::



## {{< iconify fa-solid:compass-drafting >}} &nbsp; Figures editing

::: {.talk-card}

### Miscellaneous

* Scientific drawing with inkscape monthly letter [here](https://dsinkscape.substack.com/about).
* Good practices regarding figure formating
  * Colour science [@crameriMisuseColourScience2020a] and colour map choices
  * 10 rules for better figures in scientific writting [@rougierTenSimpleRules2014a]
  * Nice tool for plotting data in latex: [PGFplot](https://pgfplots.net/)

:::