---
# title: Archive of past seminars
format:
  html:
    page-layout: full
---

## {{< iconify fa6-solid:clock-rotate-left >}} &nbsp; Archive of past talks

:::: {.talk-card}

### LMS internal (Moderator: Kostas Danas)

**Title:** Architected materials <br>
**Date:** December 4, 2025 

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1204-internal-architected/01lms-seminar-internal.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="slides"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/xZ7CanJt3itTNQf){.button target="_blank"}

:::

::::

:::: {.talk-card}

### Vito Rubino (Ecole Centrale Nantes)
 
**Title:** Dynamic rupture behavior and friction evolution revealed by laboratory experiments using ultra high-speed digital image correlation <br>
**Date:** November 20, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1120-VitoRubino/01-lms-seminar-external.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="slides"></iconify-icon> Slides](https://sdrive.cnrs.fr/s/Dpy3qaj3A5NggXN){.button target="_blank"}

:::

::::

:::: {.talk-card}

### LMS internal (Moderator: Julie Diani)

**Title:** Microstructures <br>
**Date:** November 06, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1106-internal-microstructures/01lms-seminar-internal.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/Xiszf9rxsFZ8KzP){.button target="_blank"}

:::

::::

:::: {.talk-card}

### Rian Seghir (Ecole Centrale Nantes)
 
**Title:** If images could talk: An image-based approach for characterizing dynamic responses in solid mechanics <br>
**Date:** October 16, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1016-RianSeghir/01lms-seminar-external.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/bpbnsH2NrYD4sn7){.button target="_blank"}

:::

::::

:::: {.talk-card}

### Burigede Liu (University of Cambridge)
 
**Title:** Operator learning in mechanics and materials <br>
**Date:** October 09, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1009-BurigedeLiu/01lms-seminar-external.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/F83JCszERFaYiFc){.button target="_blank"}

:::

::::

:::: {.talk-card}

### Jonathan Cormier (ISAE-ENSMA)
 
**Title:** Factors controlling VHCF life of Ni-based single crystal superalloys <br>
**Date:** October 02, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-1002-JonathanCormier/01lms-seminar-external.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/byzeBfe2EBkoDaq){.button target="_blank"}

:::

::::

::::: {.talk-card}

### LMS internal (Moderator: Laurent Guin)

**Title:** Multi-physical coupling in mechanics <br>
**Date:** September 25, 2025 

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-0924-lms-internal-multiphysics/lms-internal-multiphysics.pdf){.button target="_blank"}

<!-- [<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/H7FDm7mdjr37dzD){.button target="_blank"} -->

:::

::::

::::: {.talk-card}

### Thomas Cornèlius (IM2NP, Aix-Marseilles University)
 
**Title:** Mechanical behavior at the nanoscale in the light of synchrotron X-ray diffraction <br>
**Date:** September 18, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-0918-ThomasCornelius/cornelius.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/H7FDm7mdjr37dzD){.button target="_blank"}

:::

::::

::::: {.talk-card}
### Thèodore Cherrière (Centrale Supèlec, France)
 
**Title:** Adjoint variable method and applications: from design optimization to force computation <br>
**Date:** September 4, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25-0904-TheodoreCherriere/cherriere.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/pEPm3rjLwFrZe97){.button target="_blank"}

:::

::::

::::: {.talk-card}
### Robert Style (ETH Zurich, Switzerland)

**Title:** How freezing breaks soft, wet materials <br>
**Date:** July 3, 2025 

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0703_RobStyle/style.pdf){.button target="_blank"}

:::


:::::

::::: {.talk-card}
### Konstantinos Karapiperis (EPFL, Switzerland)

**Title:** Physics-informed data-driven modeling for the mechanics of soils and structures <br>
**Date:** June 26, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0626_Kostas/kostas.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Francois Barthelat (University of Colorado, Boulder, U.S.A.)

**Title:** Two examples of granular materials “engineered” for strength: Granular crystals, entangled matter <br>
**Date:** June 19, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0619_FrancoisBarthelat/barthelat.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Antonio Somma (Ecole Polytechnique, France)

**Title:** Haptics and music <br>
**Date:** June 12, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Samuel Forest (Centre de Matèriaux, Mines Paris PSL, France)

**Title:** Stored energy vs dissipation in gradient crystal plasticity: Application to cyclic plasticity and recrystallization <br>
**Date:** June 05, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0605_SamuelForest/forest.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Christos Vassilicos (LFML, Lille, France)

**Title:** A certain prediction of production of uncertainty <br>
**Date:** May 22, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0522_ChristosVassilicos/vassilicos.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Min Wu (Worcester Polytechnic Institute, U.S.A.)

**Title:** Continuum Modeling of Mechanical Feedback and Stress Relaxation in Growth-Elasticity: Theory and Applications <br>
**Date:** May 15, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0515_MinWu/wu.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}
### Christian Franck (University of Wisconsin-Madison, U.S.A.)

**Title:** Inertial cavitation in Soft Matter – Friend or Foe? <br>
**Date:** May 15, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0408_ChristianFranck/franck.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/3Sr4SYF7KWCW5xE){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Francois Hild (Laboratoire de Mècanique Paris-Saclay, France)
 
**Title:** Contributions of 4D imaging in mechanics of materials <br>
**Date:** March 20, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0320_FrancoisHild/hild.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/fWfTiXfT2sid4WW){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Maria Teresa Pèrez Prado (IMDEA Materials Institute, Spain)

**Title:** Metallurgy meets architecture: Unlocking the potential of 3D-printed metamaterials <br>
**Date:** March 13, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0313_MariaTeresa/teresa.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/6P8LBtENDWjcKyA){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Marc Geers (TU Eindhoven, Netherlands)
 
**Title:** A continuum consistent particle method for discrete fracture events and phase transformations in silicon <br>
**Date:** March 06, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0306_MarcGeers/geers.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### John Kolinski (EPFL Lausanne, Switzerland)

**Title:** Make it and break it: Contact and Cracks at soft interfaces <br>
**Date:** February 27, 2025 

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0227_JohnKolinski/kolinski.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Harsha Bhat (Ecole Normale Supèrieure, France)
 
**Title:** Fault Volume:  A paradigm for  Reconciling Modern Observations of Active Faults <br>
**Date:** February 13, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/KSLepEsCJyeRxof){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Arthur Lebèe (Ecole nationale des ponts et chaussées, France)

**Title:** Characterization of rolling and longitudinal shear creep for cross-laminated timber panels <br>
**Date:** February 06, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0206_ArthurLebee/lebee.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Gwennou Coupier (University of Grenoble-Alpes, France)

**Title:** Flow generation through buckling instability: from beach balls to microswimmers <br>
**Date:** January 23, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0123_GwennouCoupier/coupier.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Antony Beris (University of Delaware, U.S.A.)

**Title:** On the use of the Single Generator Bracket Formalism of Non-Equilibrium Thermodynamics for the development of the equations of Continuum Mechanics <br>
**Date:** January 16, 2025 

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0113_AntonyBeris/beris.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/XkS27xSAR86TKf7){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Laurent Stainier (Ecole Centrale Nantes, France)
 
**Title:** Data-driven computational mechanics and physics of materials <br>
**Date:** January 09, 2025

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/25_0109_LaurentStainier/stainier.pdf){.button target="_blank"}


:::

:::::

::::: {.talk-card}

### Marie A. Charpagne (University of Illinois at Urbana-Champaign, U.S.A.)
 
**Title:** Grain boundary engineering in metal additive manufacturing <br>
**Date:** December 19, 2024

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/24_1912_MarieACharpagne/charpagne.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Triona Lally (Trinity College Dublin)
 
**Title:** Made to measure: Designing and optimising 3D printed patient specific stents <br>
**Date:** December 11, 2024

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/24_1211_MECA_TrionaLally/lally.pdf){.button target="_blank"}

:::

:::::

::::: {.talk-card}

### Joint talk: John Hutchinson (Harvard University, U.S.A.) and Pedro Reis (EPFL, Lausanne, Switzerland)
 
**Title:** Imperfection Sensitivity in Shell Buckling: Longstanding Questions and New Answers <br>
**Date:** December 05, 2024

::: {.button}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="announcement"></iconify-icon> Announcement](Resources/lms-seminar-docs/docs/AbstractsProfileAnnouncements/24_1205_PedroReis/24_1205_PedroResiJohnHutchinson.pdf){.button target="_blank"}

[<iconify-icon icon="fa-solid:chalkboard" aria-label="recording"></iconify-icon> Recording](https://sdrive.cnrs.fr/s/tErLGesFbNraARg){.button target="_blank"}

:::

:::::